### ISSUE TITLE
[Suggestion] Configurable Default Launch Mode

### ISSUE THREAD

**Issue by 1A3Dev** [flerouwu/LC_FastStartup#1]
Would be nice for development purposes if there was a config option to select the default Launch Mode.

**Comment by flerouwu** [comment]
Thanks for the suggestion! Expect an update later today that should add this.

**Comment by flerouwu** [comment]
The config update is now uploaded on Thunderstore. It still defaults to launching into Online mode, but you can change it to Lan in `BepInEx/config/dev.flero.lethal.FastStartup.cfg`.

Thunderstore seems to be taking sometime to update the page for me, however you can manually download the files below:
https://github.com/flerouwu/LC_FastStartup/releases/tag/1.1.0
https://thunderstore.io/package/download/flerouwu/LC_FastStartup/1.1.0/
