### ISSUE TITLE
Works, but getting a NullReferenceException

### ISSUE THREAD

**Issue by Snayler** [flerouwu/LC_FastStartup#4]
The mod works great, I'm just getting the following error on console:
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
IngamePlayerSettings+<waitToLoadSettings>d__17.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)`

Tested with a fresh profile with only Bepinex and LC_FastStartup.

**Comment by flerouwu** [comment]
Thanks for reporting this! I am aware of this issue, and have been looking into it. However, I haven't seen any issues with the game regarding this yet, so it's not of high important currently.

If you find anything that is abnormal, add a comment and I'll look into it!

**Comment by flerouwu** [comment]
This issue has been fixed in the latest version (1.1.2). I've uploaded it to Thunderstore.
You can view the available versions at https://thunderstore.io/c/lethal-company/p/flerouwu/LC_FastStartup/versions/
