### ISSUE TITLE
[Bug] LethalLanFix erroring if Lan Warning Popup is destroyed.

### ISSUE THREAD

**Issue by darthalex2014** [flerouwu/LC_FastStartup#5]
Your mod in Lan mode (in config set Lan) breaks mod LethalLanFix, when you click to join should pop up a window to enter the ip address. But it does not.

https://thunderstore.io/c/lethal-company/p/BepInEx/BepInEx_MLLoader/
https://thunderstore.io/c/lethal-company/p/jghx777/LethalLanFix/

**Comment by flerouwu** [comment]
I am unable to get LethalLanFix to work even without FastStartup installed. There are no log messages printed that the decompiled DLL shows it should output.

Can you confirm that it works without FastStartup installed? If so, how is your mods setup? (What mod manager, how is LethalLanFix installed?)

**Comment by darthalex2014** [comment]
> Can you confirm that it works without FastStartup installed?

Tried it on a perfectly clean game clint.
BepInEx-BepInExPack
BepInEx MLLoader
LethalLanFix
and your mod

Yes, its work. (without your mod)
![image](https://github.com/flerouwu/LC_FastStartup/assets/51307259/5f7f6833-36f6-42b1-a5ee-8abfe85acea0)

Have you installed the BepInEx MLLoader?
https://thunderstore.io/c/lethal-company/p/BepInEx/BepInEx_MLLoader/
You have to manually install it, not through the mod manager.
If you have installed BepInEx MLLoader correctly
it will look like this separate MLLoader folder:
(also folders inside BepInEx).
![image](https://github.com/flerouwu/LC_FastStartup/assets/51307259/7db39e7b-8dc4-4f95-8c7a-c2ac5f9c3a42)

LethalLanFix should be installed on top of it. 
(also manually in the MLLoader folder).
https://thunderstore.io/c/lethal-company/p/jghx777/LethalLanFix/

[BepInEx-BepInExPack-5.4.2100_and_BepInEx-BepInEx_MLLoader-2.1.0_and_jghx777-LethalLanFix-1.1.0.zip](https://github.com/flerouwu/LC_FastStartup/files/14565603/BepInEx-BepInExPack-5.4.2100_and_BepInEx-BepInEx_MLLoader-2.1.0_and_jghx777-LethalLanFix-1.1.0.zip)
Here's a finished build of 3 of these mods to make it clear how they stand together.
BepInEx-BepInExPack
BepInEx MLLoader
LethalLanFix

**Comment by flerouwu** [comment]
Thanks for the help! I managed to get LethalLanFix working without FastStartup installed.

LethalLanFix can be fixed by disabling the `DisableLanPopup` config value in FastStartup. Unfortunately, I haven't found any other way to enable LethalLanFix to continue working with this config option enabled.
